spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VictorVillazante/git-config-server
          default-label: "main"
server:
  port: 8888
