spring:
  application:
    name: ms-discovery

server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
                    #http://localhost:8761/eureka/
  server:
    enable-self-preservation: false


